from database.database import Base, SessionLocal, engine
from models.models import Product, Promotion

# Base.metadata.create_all(bind=engine)

db = SessionLocal()

produtos = [
    Produto(
        nome="Molho de Tomate Tradicional",
        categoria="Molhos",
        marca="Predilecta",
        preco=5.49,
        quantidade="340g",
    ),
    Produto(
        nome="Passata de Tomate",
        categoria="Molhos",
        marca="Heinz",
        preco=7.99,
        quantidade="500ml",
    ),
    Produto(
        nome="Massa para Lasanha",
        categoria="Massas",
        marca="Dona Benta",
        preco=4.50,
        quantidade="500g",
    ),
    Produto(
        nome="Lasanha",
        categoria="Massas",
        marca="Barilla",
        preco=6.20,
        quantidade="500g",
    ),
    Produto(
        nome="Macarrão Espaguete",
        categoria="Massas",
        marca="Renata",
        preco=4.00,
        quantidade="500g",
    ),
    Produto(
        nome="Arroz Branco Tipo 1",
        categoria="Grãos",
        marca="Tio João",
        preco=22.90,
        quantidade="5kg",
    ),
    Produto(
        nome="Feijão Carioca",
        categoria="Grãos",
        marca="Kicaldo",
        preco=8.50,
        quantidade="1kg",
    ),
    Produto(
        nome="Farinha de Trigo",
        categoria="Farinhas",
        marca="Dona Benta",
        preco=5.60,
        quantidade="1kg",
    ),
    Produto(
        nome="Fermento Biológico Seco",
        categoria="Farinhas",
        marca="Fleischmann",
        preco=3.50,
        quantidade="10g",
    ),
    Produto(
        nome="Açúcar Refinado",
        categoria="Açúcar",
        marca="União",
        preco=4.20,
        quantidade="1kg",
    ),
    Produto(
        nome="Sal Refinado",
        categoria="Temperos",
        marca="Cisne",
        preco=2.10,
        quantidade="1kg",
    ),
    Produto(
        nome="Óleo de Soja",
        categoria="Óleos",
        marca="Liza",
        preco=6.30,
        quantidade="900ml",
    ),
    Produto(
        nome="Leite Integral",
        categoria="Laticínios",
        marca="Parmalat",
        preco=4.80,
        quantidade="1L",
    ),
    Produto(
        nome="Manteiga com Sal",
        categoria="Laticínios",
        marca="Aviação",
        preco=9.90,
        quantidade="200g",
    ),
    Produto(
        nome="Creme de Leite",
        categoria="Laticínios",
        marca="Nestlé",
        preco=3.80,
        quantidade="200g",
    ),
    Produto(
        nome="Queijo Mussarela Ralada",
        categoria="Queijos",
        marca="Polenghi",
        preco=12.00,
        quantidade="200g",
    ),
    Produto(
        nome="Queijo Parmesão Ralado",
        categoria="Queijos",
        marca="Faixa Azul",
        preco=7.50,
        quantidade="50g",
    ),
    Produto(
        nome="Presunto Fatiado",
        categoria="Frios",
        marca="Sadia",
        preco=6.00,
        quantidade="200g",
    ),
    Produto(
        nome="Carne Moída de Patinho",
        categoria="Carnes e proteínas",
        marca="Friboi",
        preco=25.00,
        quantidade="1kg",
    ),
    Produto(
        nome="Frango em Cubos",
        categoria="Carnes e proteínas",
        marca="Sadia",
        preco=18.00,
        quantidade="1kg",
    ),
    Produto(
        nome="Peito de Frango",
        categoria="Carnes e proteínas",
        marca="Seara",
        preco=16.50,
        quantidade="1kg",
    ),
    Produto(
        nome="Atum em Lata",
        categoria="Enlatados",
        marca="Gomes da Costa",
        preco=7.20,
        quantidade="170g",
    ),
    Produto(
        nome="Milho Verde em Conserva",
        categoria="Enlatados",
        marca="Quero",
        preco=3.10,
        quantidade="170g",
    ),
    Produto(
        nome="Ervilha em Conserva",
        categoria="Enlatados",
        marca="Quero",
        preco=3.20,
        quantidade="170g",
    ),
    Produto(
        nome="Batata Inglesa",
        categoria="Hortifruti",
        marca="Natural",
        preco=4.00,
        quantidade="1kg",
    ),
    Produto(
        nome="Cebola",
        categoria="Hortifruti",
        marca="Natural",
        preco=3.50,
        quantidade="1kg",
    ),
    Produto(
        nome="Alho",
        categoria="Hortifruti",
        marca="Natural",
        preco=2.00,
        quantidade="100g",
    ),
    Produto(
        nome="Cenoura",
        categoria="Hortifruti",
        marca="Natural",
        preco=3.80,
        quantidade="1kg",
    ),
    Produto(
        nome="Ovos Brancos",
        categoria="Ovos",
        marca="Granja São José",
        preco=12.00,
        quantidade="12 unidades",
    ),
    Produto(
        nome="Iogurte Natural",
        categoria="Laticínios",
        marca="Vigor",
        preco=2.80,
        quantidade="170g",
    ),
    Produto(
        nome="Maionese",
        categoria="Condimentos",
        marca="Hellmann's",
        preco=8.00,
        quantidade="500g",
    ),
    Produto(
        nome="Ketchup",
        categoria="Condimentos",
        marca="Heinz",
        preco=7.00,
        quantidade="397g",
    ),
    Produto(
        nome="Mostarda",
        categoria="Condimentos",
        marca="Heinz",
        preco=6.50,
        quantidade="255g",
    ),
    Produto(
        nome="Refrigerante Cola",
        categoria="Bebidas",
        marca="Coca-Cola",
        preco=8.00,
        quantidade="2L",
    ),
    Produto(
        nome="Água Mineral sem Gás",
        categoria="Bebidas",
        marca="Crystal",
        preco=2.50,
        quantidade="500ml",
    ),
    Produto(
        nome="Café Torrado e Moído",
        categoria="Bebidas",
        marca="Pilão",
        preco=13.00,
        quantidade="500g",
    ),
    Produto(
        nome="Chá Mate",
        categoria="Bebidas",
        marca="Leão",
        preco=5.00,
        quantidade="25 sachês",
    ),
    Produto(
        nome="Biscoito Cream Cracker",
        categoria="Biscoitos",
        marca="Vitarella",
        preco=3.80,
        quantidade="400g",
    ),
    Produto(
        nome="Chocolate ao Leite",
        categoria="Doces",
        marca="Lacta",
        preco=6.50,
        quantidade="90g",
    ),
    # Novos produtos adicionados
    Produto(
        nome="Pão de Forma",
        categoria="Padaria",
        marca="Pullman",
        preco=7.50,
        quantidade="500g",
    ),
    Produto(
        nome="Hambúrguer Bovino",
        categoria="Carnes e proteínas",
        marca="Seara",
        preco=18.00,
        quantidade="672g",
    ),
    Produto(
        nome="Salsicha",
        categoria="Carnes e proteínas",
        marca="Perdigão",
        preco=9.00,
        quantidade="500g",
    ),
    Produto(
        nome="Molho Shoyu",
        categoria="Molhos",
        marca="Sakura",
        preco=5.00,
        quantidade="150ml",
    ),
    Produto(
        nome="Azeite de Oliva Extra Virgem",
        categoria="Óleos",
        marca="Andorinha",
        preco=22.00,
        quantidade="500ml",
    ),
    Produto(
        nome="Vinagre de Álcool",
        categoria="Temperos",
        marca="Castelo",
        preco=3.00,
        quantidade="750ml",
    ),
    Produto(
        nome="Queijo Prato Fatiado",
        categoria="Queijos",
        marca="Polenghi",
        preco=13.00,
        quantidade="150g",
    ),
    Produto(
        nome="Banana Prata",
        categoria="Hortifruti",
        marca="Natural",
        preco=5.00,
        quantidade="1kg",
    ),
    Produto(
        nome="Maçã Fuji",
        categoria="Hortifruti",
        marca="Natural",
        preco=7.00,
        quantidade="1kg",
    ),
    Produto(
        nome="Tomate Italiano",
        categoria="Hortifruti",
        marca="Natural",
        preco=6.00,
        quantidade="1kg",
    ),
    Produto(
        nome="Pepino",
        categoria="Hortifruti",
        marca="Natural",
        preco=4.50,
        quantidade="1kg",
    ),
    Produto(
        nome="Laranja Pera",
        categoria="Hortifruti",
        marca="Natural",
        preco=4.80,
        quantidade="1kg",
    ),
    Produto(
        nome="Papel Toalha",
        categoria="Limpeza",
        marca="Snob",
        preco=6.00,
        quantidade="2 rolos",
    ),
    Produto(
        nome="Detergente Líquido",
        categoria="Limpeza",
        marca="Ypê",
        preco=2.50,
        quantidade="500ml",
    ),
    Produto(
        nome="Sabão em Pó",
        categoria="Limpeza",
        marca="Omo",
        preco=18.00,
        quantidade="800g",
    ),
    Produto(
        nome="Desinfetante",
        categoria="Limpeza",
        marca="Veja",
        preco=7.00,
        quantidade="1L",
    ),
]

produtos.extend(
    [
        Produto(
            nome="Arroz Parboilizado",
            categoria="Grãos",
            marca="Camil",
            preco=23.90,
            quantidade="5kg",
        ),
        Produto(
            nome="Feijão Preto",
            categoria="Grãos",
            marca="Kicaldo",
            preco=9.50,
            quantidade="1kg",
        ),
        Produto(
            nome="Farinha de Mandioca",
            categoria="Farinhas",
            marca="Yoki",
            preco=6.00,
            quantidade="1kg",
        ),
        Produto(
            nome="Açúcar Cristal",
            categoria="Açúcar",
            marca="Caravelas",
            preco=4.00,
            quantidade="1kg",
        ),
        Produto(
            nome="Sal Grosso",
            categoria="Temperos",
            marca="Cisne",
            preco=3.00,
            quantidade="1kg",
        ),
        Produto(
            nome="Óleo de Milho",
            categoria="Óleos",
            marca="Liza",
            preco=8.50,
            quantidade="900ml",
        ),
        Produto(
            nome="Café Solúvel",
            categoria="Bebidas",
            marca="Nescafé",
            preco=7.00,
            quantidade="50g",
        ),
        Produto(
            nome="Leite em Pó Integral",
            categoria="Laticínios",
            marca="Ninho",
            preco=18.00,
            quantidade="400g",
        ),
        Produto(
            nome="Macarrão Penne",
            categoria="Massas",
            marca="Renata",
            preco=4.20,
            quantidade="500g",
        ),
        Produto(
            nome="Polpa de Tomate",
            categoria="Molhos",
            marca="Elefante",
            preco=4.50,
            quantidade="340g",
        ),
        Produto(
            nome="Extrato de Tomate",
            categoria="Molhos",
            marca="Elefante",
            preco=3.80,
            quantidade="130g",
        ),
        Produto(
            nome="Batata Palha",
            categoria="Aperitivos",
            marca="Elma Chips",
            preco=7.00,
            quantidade="120g",
        ),
        Produto(
            nome="Farofa Pronta",
            categoria="Farinhas",
            marca="Yoki",
            preco=7.50,
            quantidade="250g",
        ),
        Produto(
            nome="Pimenta-do-Reino Moída",
            categoria="Temperos",
            marca="Kitano",
            preco=3.50,
            quantidade="30g",
        ),
        Produto(
            nome="Colorau",
            categoria="Temperos",
            marca="Kitano",
            preco=2.50,
            quantidade="50g",
        ),
        Produto(
            nome="Fermento em Pó Químico",
            categoria="Farinhas",
            marca="Dr. Oetker",
            preco=2.80,
            quantidade="100g",
        ),
        Produto(
            nome="Leite Condensado",
            categoria="Laticínios",
            marca="Moça",
            preco=7.00,
            quantidade="395g",
        ),
        Produto(
            nome="Creme de Leite UHT",
            categoria="Laticínios",
            marca="Nestlé",
            preco=4.00,
            quantidade="200g",
        ),
        Produto(
            nome="Sardinha em Lata",
            categoria="Enlatados",
            marca="Coqueiro",
            preco=5.00,
            quantidade="125g",
        ),
        Produto(
            nome="Margarina",
            categoria="Laticínios",
            marca="Qualy",
            preco=6.00,
            quantidade="500g",
        ),
        Produto(
            nome="Alho Triturado",
            categoria="Temperos",
            marca="Quero",
            preco=4.00,
            quantidade="200g",
        ),
        Produto(
            nome="Cebola em Pó",
            categoria="Temperos",
            marca="Kitano",
            preco=3.00,
            quantidade="60g",
        ),
        Produto(
            nome="Salsinha Desidratada",
            categoria="Temperos",
            marca="Kitano",
            preco=2.50,
            quantidade="10g",
        ),
        Produto(
            nome="Caldo de Galinha",
            categoria="Temperos",
            marca="Knorr",
            preco=2.00,
            quantidade="57g",
        ),
        Produto(
            nome="Caldo de Carne",
            categoria="Temperos",
            marca="Knorr",
            preco=2.00,
            quantidade="57g",
        ),
        Produto(
            nome="Fubá de Milho",
            categoria="Farinhas",
            marca="Yoki",
            preco=4.00,
            quantidade="1kg",
        ),
        Produto(
            nome="Polvilho Doce",
            categoria="Farinhas",
            marca="Amafil",
            preco=5.00,
            quantidade="500g",
        ),
        Produto(
            nome="Polvilho Azedo",
            categoria="Farinhas",
            marca="Amafil",
            preco=5.00,
            quantidade="500g",
        ),
        Produto(
            nome="Biscoito de Maisena",
            categoria="Biscoitos",
            marca="Piraquê",
            preco=4.00,
            quantidade="200g",
        ),
        Produto(
            nome="Adoçante Líquido",
            categoria="Açúcar",
            marca="Linea",
            preco=8.00,
            quantidade="75ml",
        ),
    ]
)

# Insere todos
db.add_all(produtos)
db.commit()

produtos_db_query = db.query(Produto).all()

promocoes = [
    Promocao(
        titulo="Semana do Molho de Tomate",
        descricao="Aproveite o molho de tomate Predilecta com 20% de desconto!",
        desconto_percentual=20.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=7),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Molho de Tomate Tradicional"),
    ),
    Promocao(
        titulo="Oferta Especial de Lasanha",
        descricao="Massa para lasanha Dona Benta com 15% off.",
        desconto_percentual=15.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=10),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Massa para Lasanha"),
    ),
    Promocao(
        titulo="Desconto em Arroz Tio João",
        descricao="Arroz Branco Tipo 1 com super desconto de 10%.",
        desconto_percentual=10.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=5),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Arroz Branco Tipo 1"),
    ),
    Promocao(
        titulo="Feijão da Semana",
        descricao="Feijão Carioca Kicaldo com 12% de desconto.",
        desconto_percentual=12.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=6),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Feijão Carioca"),
    ),
    Promocao(
        titulo="Oferta no Óleo Liza",
        descricao="Óleo de soja Liza com 18% de desconto.",
        desconto_percentual=18.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=7),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Óleo de Soja"),
    ),
    Promocao(
        titulo="Semana do Leite Parmalat",
        descricao="Leite Integral Parmalat com 10% off.",
        desconto_percentual=10.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=4),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Leite Integral"),
    ),
    Promocao(
        titulo="Chá Leão em Oferta",
        descricao="Leve mais pagando menos: 25% de desconto no Chá Mate Leão.",
        desconto_percentual=25.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=8),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Chá Mate"),
    ),
    Promocao(
        titulo="Desconto no Queijo Polenghi",
        descricao="Queijo mussarela ralado Polenghi com 20% de desconto.",
        desconto_percentual=20.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=5),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Queijo Mussarela Ralada"),
    ),
    Promocao(
        titulo="Promoção do Café Pilão",
        descricao="Café torrado e moído com 10% off.",
        desconto_percentual=10.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=6),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Café Torrado e Moído"),
    ),
    Promocao(
        titulo="Açúcar União em Promoção",
        descricao="Leve 1kg de açúcar refinado com 5% de desconto!",
        desconto_percentual=5.0,
        data_inicio=datetime.now(),
        data_fim=datetime.now() + timedelta(days=3),
        produto_id=next(p.id for p in produtos_db_query if p.nome == "Açúcar Refinado"),
    ),
]

db.add_all(promocoes)
db.commit()

db.close()

print(f"{len(produtos)} produtos inseridos no banco.")
print(f"{len(promocoes)} promocoes inseridas no banco.")